name: Deploy Learnerium to Live Server

on:
  push:
    branches:
      - production

jobs:
  web-deploy:
    name: 🚀 Sync Approved Code to TrueHost
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files over FTP
      uses: SamKirland/ftp-deploy-action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        protocol: ftp
        server-dir: /learnerium.jlm.com.ng/
        exclude: |
          **/.git**
          **/.git*/**
          **/.env**
          **/node_modules/**
          **/vendor/**
          **/storage/*.key
